version: '3.8'

services:
  pangeaco-ops-geosolution:
    container_name: pangeaco-ops-geosolution
    image: pangeaco-ops-geosolution
    build: .
    ports:
      - "3005:3005"
    env_file:
      - .env.local